Work around a strange compiler issue.
The MPI build bot complains that using a {...} initializer list would require the use
of a conversion constructor marked as 'explicit':

data_out_base.cc:1156:29: error: converting to ‘std::tuple<unsigned int, unsigned int>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = unsigned int&; _U2 = unsigned int&; <template-parameter-2-3> = void; _T1 = unsigned int; _T2 = unsigned int]’

That makes no sense, but let's appease the compiler by being explicit.