Tests: optimization/* add missing include
Some of the optimization tests use a std::function object but forget to
include the header. These tests work with older versions of libstdc++
due to some transitive include but fail for current versions:

/home/testsuite/workspace/regression_tests/dealii/include/deal.II/optimization/line_minimization.h:323:16: error: 'function' in namespace 'std' does not name a template type
  323 |     const std::function<std::pair<NumberType, NumberType>(const NumberType x)>
      |                ^~~~~~~~
/home/testsuite/workspace/regression_tests/dealii/include/deal.II/optimization/line_minimization.h:30:1: note: 'std::function' is defined in header '<functional>'; did you forget to '#include <functional>'?
   29 | #include <fstream>
  +++ |+#include <functional>
   30 | #include <limits>